name = "PopSimIBX"
uuid = "88d7705d-7f72-40d5-8927-d9bc8cbe062a"
authors = ["Peter Arndt <arndt@molgen.mpg.de> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34"
Distributions = "0.25"
julia = "1.6"
